@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "rafael.brito@email.com",
  "password": "123123",
  "firstName": "Rafael",
  "lastName": "Brito",
  "userType": "PROFESSIONAL"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "rafael.brito@email.com",
  "password": "123123"
}

###

# @name create_exercise
POST {{baseUrl}}/exercises
Content-Type: application/json
Authorization: Bearer {{authToken}}


