@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "rafael.brito@email.com",
  "password": "@123Rafa",
  "firstName": "Rafael",
  "lastName": "Brito",
  "userType": "PROFESSIONAL"
}

###

# @name update_user_profile
PUT {{baseUrl}}/users/profile
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "firstName": "Rafagui",
  "lastName": "Souza",
  "email": "rafael.souza@email.com"
}

###

# @name update_user_password
PATCH {{baseUrl}}/users/password
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "oldPassword": "@123Rafa",
  "newPassword": "@456Rafa"
}

###

# # @name update_user_avatar
# PUT {{baseUrl}}/users/avatar
# Content-Type: multipart/form-data
# Authorization Bearer {{authToken}}

# {
#   "avatar": "avatar.jpg"
# }

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "rafael.brito@email.com",
  "password": "@123Rafa"
}

###

# @name create_exercise
POST {{baseUrl}}/exercises
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "no reto cabe nada",
  "descriptaaaaaaaaaaaion": "exercicio pra pompoarasdasasdasd"
}
